### ISSUE TITLE
xUnit, yUnit, zUnit?

### ISSUE THREAD

**Issue by andcastillo** [cheminfo/jcampconverter#3]
There is something wrong with the reported units in the 2D spectrum. For 1D it is OK to have xUnits for direct dimension and yUnits for the dependent variable.
For 2D, xUnits should make reference to direct dimension F2, yUnits to indirect dimension F1, and zUnits for the dependent variable. 
I would prefer for 2D F2Units=xUnits, F1Units=indirect dimension units, yUnits = dependent variable units.

The current units for an HMBC spectrum is:  
  xUnit: 'PPM',
  yUnit: 'ARBITRARY',

**Comment by lpatiny** [comment]
Because we report the unit of one "subspectra" it is I think correct. Now we could indeed add at the level of spectra somethinlse like xUnits, yUnits zUnits
Currently we have xType and yType

**Comment by andcastillo** [comment]
Right.  That I agree in both things.

**Comment by lpatiny** [comment]
ntuples containing all the information has been added in the result
