### ISSUE TITLE
For some jcamps nucleus is undefined.

### ISSUE THREAD

**Issue by jobo322** [cheminfo/jcampconverter#39]
you can find an example in this [ticket](https://github.com/cheminfo/nmrium/issues/996).

the problem appear in [postProcessingNMR](https://github.com/cheminfo/jcampconverter/blob/master/src/postProcessingNMR.js#L44-L56)

**Comment by lpatiny** [comment]
Temporary fixed by eb9a7b7faf13dfa52e1c78b7ec638efcf18ee364.

But I'm afraid there will be more failing jcamps
