### ISSUE TITLE
Convert function won't work properly without ##NPOINTS

### ISSUE THREAD

**Issue by vlad-ciorba** [cheminfo/jcampconverter#58]
I updated the library from 5.0.1 to the latest version and it looks like convert function won't work properly without ##NPOINTS anymore.

On the converted object, spectra.deltaX gets the NaN value if the ##NPOINTS is unset, even through the ##DELTAX has a value.

**Comment by lpatiny** [comment]
could you zip add attached sour file here ? From which instrument it is generated ?

**Comment by vlad-ciorba** [comment]
It was generated with an Serstech 100 Indicator.

Input:
> ##TITLE=referenceSpectrum
> ##DELTAX=2
> ##FIRSTX=400
> ##LASTX=2302
> ##XYDATA=(X++(Y..Y))
> 400 2861 2861 2861 2861 2861 2861 2861 3294 3623 3994 4536 4952 5364 5562 5842 5994 6263 6535 6993 7610 8368 9164 10006 10870 11849 12586 13494 14211 14937 15633 16255 16868 17694 18640 19698 20892 22154 23295 24076 24384 24252 23768 22870 21821 20601 19445 18354 17286 16364 15725 15222 14918 14837 14798 14936 15059 15005 14814 14630 14100 13389 12667 11835 10893 9832 8724 7714 6965 6224 5642 5596 5692 5705 5657 5660 5602 5506 5303 5074 4951 4780 4512 4155 3980 3770 3502 3340 3104 2904 2682 2473 2179 1956 1874 1733 1776 1692 1625 1570 1498 1367 1294 1324 1298 1319 1258 1279 1269 1326 1338 1344 1332 1313 1341 1340 1372 1475 1574 1673 1778 1866 2013 2085 2132 2258 2421 2487 2770 3035 3244 3374 3472 3480 3373 3064 2692 2482 2144 1911 1694 1611 1560 1569 1520 1491 1470 1377 1324 1204 1147 1144 1119 1080 1087 1061 1064 1095 1101 1132 1119 1102 1125 1120 1115 1111 1079 1106 1147 1112 1118 1143 1131 1147 1110 1078 1085 1157 1168 1173 1196 1244 1325 1361 1496 1688 1942 2271 2654 3194 3805 4559 5507 6566 7663 8953 10331 11904 13586 15497 17505 19544 21313 22820 23913 24742 25481 26192 27253 28206 29056 29601 29953 29871 29937 30316 31348 33361 35805 38517 41000 42967 44558 45874 47032 48579 50268 51758 52833 53173 52354 50350 47342 43500 39108 34337 29290 24457 19983 16171 13067 10914 9782 9422 9617 10084 10809 11550 12496 13447 14715 16358 18034 19818 21355 22473 23024 23132 22879 22574 22157 21664 21466 21332 21176 20818 20384 19736 18957 17987 17085 16237 15554 15046 14678 14565 14717 14916 15457 16078 16654 17011 17176 17173 16931 16341 15262 13988 12429 10677 8800 7248 5832 4690 3916 3135 2610 2204 1936 1753 1763 1816 1763 1612 1415 1241 1051 1014 1015 954 907 728 495 297 149 0 41 184 321 652 982 1498 2090 2726 3587 4721 6019 7410 8916 10341 11713 12818 13682 14479 15165 15764 16353 16974 17612 18309 19068 19870 20703 21621 22592 23354 23828 24044 23845 23509 22968 22348 21740 21427 21164 21013 20904 20894 20986 20925 20753 20478 20150 19672 19166 18718 18312 18087 17809 17521 17266 16969 16670 16405 16429 16582 16809 17184 17421 17440 17164 16605 15754 14861 13822 12405 10851 9024 7226 5505 3778 2556 1551 905 404 111 39 156 372 982 1673 2248 2574 2763 2569 2195 1525 914 497 166 16 39 316 644 1167 1801 2653 3735 4881 5961 6954 7842 8591 9293 9817 10142 10420 10394 10194 9785 9477 9077 8890 8709 8451 8162 7841 7471 6986 6622 6502 6619 6507 6759 6933 7085 7241 7422 7652 7933 8088 8003 8015 7844 7669 7407 7111 6617 6264 6065 5803 5719 5668 5696 5683 5686 6022 6433 6908 7330 7838 8372 8970 9734 10519 11327 11452 11346 10854 10134 9205 8608 8039 7810 7573 7397 7324 7206 7097 6799 6499 6361 6388 6295 6272 6461 6677 6871 6869 6945 6986 6907 6854 6775 6759 6847 6942 6866 6912 6859 6695 6537 6449 6661 7317 8367 9926 11933 14710 17855 21580 25578 29750 33822 37548 40851 43364 45309 46521 46660 45940 44554 42630 40365 37924 35269 32714 30200 27834 25423 22900 20123 17319 14550 11773 9208 7071 5540 4406 3533 2837 2396 2171 1857 1554 1335 1125 939 800 775 687 700 648 615 599 599 624 627 597 564 561 568 604 609 579 557 549 544 624 633 718 803 834 854 823 791 765 772 742 746 820 832 858 867 871 861 856 901 948 974 1000 1000 1044 1088 1106 1133 1161 1161 1170 1171 1146 1172 1214 1251 1259 1309 1340 1368 1381 1407 1403 1430 1439 1439 1472 1487 1501 1525 1570 1591 1625 1690 1726 1738 1780 1832 1836 1860 1837 1823 1833 1792 1768 1830 1883 1911 1916 1923 1930 1921 1915 1931 1943 1981 2000 2012 2020 2061 2081 2089 2086 2072 2101 2114 2122 2137 2174 2182 2174 2187 2201 2222 2237 2253 2244 2240 2234 2255 2279 2300 2290 2285 2284 2282 2303 2333 2374 2410 2418 2435 2435 2447 2452 2455 2480 2490 2478 2472 2481 2492 2524 2556 2566 2579 2563 2569 2583 2592 2605 2629 2641 2638 2633 2619 2630 2646 2676 2695 2725 2726 2726 2716 2701 2693 2686 2703 2706 2704 2703 2696 2696 2683 2685 2705 2732 2728 2732 2736 2719 2739 2729 2746 2760 2761 2725 2721 2655 2703 2771 2808 2820 2818 2814 2793 2760 2704 2728 2718 2698 2665 2655 2648 2661 2672 2682 2693 2694 2698 2700 2714 2701 2689 2684 2664 2629 2610 2596 2594 2598 2585 2579 2573 2560 2542 2559 2548 2540 2533 2517 2513 2496 2518 2505 2504 2491 2462 2454 2435 2427 2434 2446 2431 2415 2408 2392 2371 2355 2349 2341 2329 2318 2316 2310 2304 2291 2283 2278 2252 2237 2230 2213 2204 2189 2183 2173 2163 2126 2098 2094 2083 2082 2056 2049 2030 2004 1987 1990 1990 1994 1995 1977 1973 1940 1901 1889 1873 1849 1835 1836 1827 1838 1824 1821 1813 1805 1794 1762 1744 1739 1726 1700 1689 1677 1653 1627 1612 1608 1612 1603 1584 1576 1581 1564 1552 1558 1557 1551 1535 1520 1520 1501 1471 1457 1455 1430 1415 1403 1397 1375 1367 1330 1335 1339 1334 1328 1339 1352 1352 1342 1327 1307 1300 1282 1262 1276 1298 1294 1299 1309 1309 1314 1308 1284 1273 1246 1247 1249 1238 1239 1270 1266 1255 1252 1237 1232 1236 1239 1236 1254 1245 1259 1281 1276 1262 1276 1284 1282 1296 1314 1337 1362 1368 1367 1376 1403 1408 1499 1499 1499 1499 1499 1499
> ##END=

Output (5.0.1):
> {"spectra":[{"deltaX":2,"firstX":400,"lastX":2302,"xFactor":1,"yFactor":1,"isXYdata":true,"data":{"x":[400,402,404,406,408,410,412,414,416,418,420,422,424,426,428,430,432,434,436,438,440,442,444,446,448,450,452,454,456,458,460,462,464,466,468,470,472,474,476,478,480,482,484,486,488,490,492,494,496,498,500,502,504,506,508,510,512,514,516,518,520,522,524,526,528,530,532,534,536,538,540,542,544,546,548,550,552,554,556,558,560,562,564,566,568,570,572,574,576,578,580,582,584,586,588,590,592,594,596,598,600,602,604,606,608,610,612,614,616,618,620,622,624,626,628,630,632,634,636,638,640,642,644,646,648,650,652,654,656,658,660,662,664,666,668,670,672,674,676,678,680,682,684,686,688,690,692,694,696,698,700,702,704,706,708,710,712,714,716,718,720,722,724,726,728,730,732,734,736,738,740,742,744,746,748,750,752,754,756,758,760,762,764,766,768,770,772,774,776,778,780,782,784,786,788,790,792,794,796,798,800,802,804,806,808,810,812,814,816,818,820,822,824,826,828,830,832,834,836,838,840,842,844,846,848,850,852,854,856,858,860,862,864,866,868,870,872,874,876,878,880,882,884,886,888,890,892,894,896,898,900,902,904,906,908,910,912,914,916,918,920,922,924,926,928,930,932,934,936,938,940,942,944,946,948,950,952,954,956,958,960,962,964,966,968,970,972,974,976,978,980,982,984,986,988,990,992,994,996,998,1000,1002,1004,1006,1008,1010,1012,1014,1016,1018,1020,1022,1024,1026,1028,1030,1032,1034,1036,1038,1040,1042,1044,1046,1048,1050,1052,1054,1056,1058,1060,1062,1064,1066,1068,1070,1072,1074,1076,1078,1080,1082,1084,1086,1088,1090,1092,1094,1096,1098,1100,1102,1104,1106,1108,1110,1112,1114,1116,1118,1120,1122,1124,1126,1128,1130,1132,1134,1136,1138,1140,1142,1144,1146,1148,1150,1152,1154,1156,1158,1160,1162,1164,1166,1168,1170,1172,1174,1176,1178,1180,1182,1184,1186,1188,1190,1192,1194,1196,1198,1200,1202,1204,1206,1208,1210,1212,1214,1216,1218,1220,1222,1224,1226,1228,1230,1232,1234,1236,1238,1240,1242,1244,1246,1248,1250,1252,1254,1256,1258,1260,1262,1264,1266,1268,1270,1272,1274,1276,1278,1280,1282,1284,1286,1288,1290,1292,1294,1296,1298,1300,1302,1304,1306,1308,1310,1312,1314,1316,1318,1320,1322,1324,1326,1328,1330,1332,1334,1336,1338,1340,1342,1344,1346,1348,1350,1352,1354,1356,1358,1360,1362,1364,1366,1368,1370,1372,1374,1376,1378,1380,1382,1384,1386,1388,1390,1392,1394,1396,1398,1400,1402,1404,1406,1408,1410,1412,1414,1416,1418,1420,1422,1424,1426,1428,1430,1432,1434,1436,1438,1440,1442,1444,1446,1448,1450,1452,1454,1456,1458,1460,1462,1464,1466,1468,1470,1472,1474,1476,1478,1480,1482,1484,1486,1488,1490,1492,1494,1496,1498,1500,1502,1504,1506,1508,1510,1512,1514,1516,1518,1520,1522,1524,1526,1528,1530,1532,1534,1536,1538,1540,1542,1544,1546,1548,1550,1552,1554,1556,1558,1560,1562,1564,1566,1568,1570,1572,1574,1576,1578,1580,1582,1584,1586,1588,1590,1592,1594,1596,1598,1600,1602,1604,1606,1608,1610,1612,1614,1616,1618,1620,1622,1624,1626,1628,1630,1632,1634,1636,1638,1640,1642,1644,1646,1648,1650,1652,1654,1656,1658,1660,1662,1664,1666,1668,1670,1672,1674,1676,1678,1680,1682,1684,1686,1688,1690,1692,1694,1696,1698,1700,1702,1704,1706,1708,1710,1712,1714,1716,1718,1720,1722,1724,1726,1728,1730,1732,1734,1736,1738,1740,1742,1744,1746,1748,1750,1752,1754,1756,1758,1760,1762,1764,1766,1768,1770,1772,1774,1776,1778,1780,1782,1784,1786,1788,1790,1792,1794,1796,1798,1800,1802,1804,1806,1808,1810,1812,1814,1816,1818,1820,1822,1824,1826,1828,1830,1832,1834,1836,1838,1840,1842,1844,1846,1848,1850,1852,1854,1856,1858,1860,1862,1864,1866,1868,1870,1872,1874,1876,1878,1880,1882,1884,1886,1888,1890,1892,1894,1896,1898,1900,1902,1904,1906,1908,1910,1912,1914,1916,1918,1920,1922,1924,1926,1928,1930,1932,1934,1936,1938,1940,1942,1944,1946,1948,1950,1952,1954,1956,1958,1960,1962,1964,1966,1968,1970,1972,1974,1976,1978,1980,1982,1984,1986,1988,1990,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016,2018,2020,2022,2024,2026,2028,2030,2032,2034,2036,2038,2040,2042,2044,2046,2048,2050,2052,2054,2056,2058,2060,2062,2064,2066,2068,2070,2072,2074,2076,2078,2080,2082,2084,2086,2088,2090,2092,2094,2096,2098,2100,2102,2104,2106,2108,2110,2112,2114,2116,2118,2120,2122,2124,2126,2128,2130,2132,2134,2136,2138,2140,2142,2144,2146,2148,2150,2152,2154,2156,2158,2160,2162,2164,2166,2168,2170,2172,2174,2176,2178,2180,2182,2184,2186,2188,2190,2192,2194,2196,2198,2200,2202,2204,2206,2208,2210,2212,2214,2216,2218,2220,2222,2224,2226,2228,2230,2232,2234,2236,2238,2240,2242,2244,2246,2248,2250,2252,2254,2256,2258,2260,2262,2264,2266,2268,2270,2272,2274,2276,2278,2280,2282,2284,2286,2288,2290,2292,2294,2296,2298,2300],"y":[2861,2861,2861,2861,2861,2861,2861,3294,3623,3994,4536,4952,5364,5562,5842,5994,6263,6535,6993,7610,8368,9164,10006,10870,11849,12586,13494,14211,14937,15633,16255,16868,17694,18640,19698,20892,22154,23295,24076,24384,24252,23768,22870,21821,20601,19445,18354,17286,16364,15725,15222,14918,14837,14798,14936,15059,15005,14814,14630,14100,13389,12667,11835,10893,9832,8724,7714,6965,6224,5642,5596,5692,5705,5657,5660,5602,5506,5303,5074,4951,4780,4512,4155,3980,3770,3502,3340,3104,2904,2682,2473,2179,1956,1874,1733,1776,1692,1625,1570,1498,1367,1294,1324,1298,1319,1258,1279,1269,1326,1338,1344,1332,1313,1341,1340,1372,1475,1574,1673,1778,1866,2013,2085,2132,2258,2421,2487,2770,3035,3244,3374,3472,3480,3373,3064,2692,2482,2144,1911,1694,1611,1560,1569,1520,1491,1470,1377,1324,1204,1147,1144,1119,1080,1087,1061,1064,1095,1101,1132,1119,1102,1125,1120,1115,1111,1079,1106,1147,1112,1118,1143,1131,1147,1110,1078,1085,1157,1168,1173,1196,1244,1325,1361,1496,1688,1942,2271,2654,3194,3805,4559,5507,6566,7663,8953,10331,11904,13586,15497,17505,19544,21313,22820,23913,24742,25481,26192,27253,28206,29056,29601,29953,29871,29937,30316,31348,33361,35805,38517,41000,42967,44558,45874,47032,48579,50268,51758,52833,53173,52354,50350,47342,43500,39108,34337,29290,24457,19983,16171,13067,10914,9782,9422,9617,10084,10809,11550,12496,13447,14715,16358,18034,19818,21355,22473,23024,23132,22879,22574,22157,21664,21466,21332,21176,20818,20384,19736,18957,17987,17085,16237,15554,15046,14678,14565,14717,14916,15457,16078,16654,17011,17176,17173,16931,16341,15262,13988,12429,10677,8800,7248,5832,4690,3916,3135,2610,2204,1936,1753,1763,1816,1763,1612,1415,1241,1051,1014,1015,954,907,728,495,297,149,0,41,184,321,652,982,1498,2090,2726,3587,4721,6019,7410,8916,10341,11713,12818,13682,14479,15165,15764,16353,16974,17612,18309,19068,19870,20703,21621,22592,23354,23828,24044,23845,23509,22968,22348,21740,21427,21164,21013,20904,20894,20986,20925,20753,20478,20150,19672,19166,18718,18312,18087,17809,17521,17266,16969,16670,16405,16429,16582,16809,17184,17421,17440,17164,16605,15754,14861,13822,12405,10851,9024,7226,5505,3778,2556,1551,905,404,111,39,156,372,982,1673,2248,2574,2763,2569,2195,1525,914,497,166,16,39,316,644,1167,1801,2653,3735,4881,5961,6954,7842,8591,9293,9817,10142,10420,10394,10194,9785,9477,9077,8890,8709,8451,8162,7841,7471,6986,6622,6502,6619,6507,6759,6933,7085,7241,7422,7652,7933,8088,8003,8015,7844,7669,7407,7111,6617,6264,6065,5803,5719,5668,5696,5683,5686,6022,6433,6908,7330,7838,8372,8970,9734,10519,11327,11452,11346,10854,10134,9205,8608,8039,7810,7573,7397,7324,7206,7097,6799,6499,6361,6388,6295,6272,6461,6677,6871,6869,6945,6986,6907,6854,6775,6759,6847,6942,6866,6912,6859,6695,6537,6449,6661,7317,8367,9926,11933,14710,17855,21580,25578,29750,33822,37548,40851,43364,45309,46521,46660,45940,44554,42630,40365,37924,35269,32714,30200,27834,25423,22900,20123,17319,14550,11773,9208,7071,5540,4406,3533,2837,2396,2171,1857,1554,1335,1125,939,800,775,687,700,648,615,599,599,624,627,597,564,561,568,604,609,579,557,549,544,624,633,718,803,834,854,823,791,765,772,742,746,820,832,858,867,871,861,856,901,948,974,1000,1000,1044,1088,1106,1133,1161,1161,1170,1171,1146,1172,1214,1251,1259,1309,1340,1368,1381,1407,1403,1430,1439,1439,1472,1487,1501,1525,1570,1591,1625,1690,1726,1738,1780,1832,1836,1860,1837,1823,1833,1792,1768,1830,1883,1911,1916,1923,1930,1921,1915,1931,1943,1981,2000,2012,2020,2061,2081,2089,2086,2072,2101,2114,2122,2137,2174,2182,2174,2187,2201,2222,2237,2253,2244,2240,2234,2255,2279,2300,2290,2285,2284,2282,2303,2333,2374,2410,2418,2435,2435,2447,2452,2455,2480,2490,2478,2472,2481,2492,2524,2556,2566,2579,2563,2569,2583,2592,2605,2629,2641,2638,2633,2619,2630,2646,2676,2695,2725,2726,2726,2716,2701,2693,2686,2703,2706,2704,2703,2696,2696,2683,2685,2705,2732,2728,2732,2736,2719,2739,2729,2746,2760,2761,2725,2721,2655,2703,2771,2808,2820,2818,2814,2793,2760,2704,2728,2718,2698,2665,2655,2648,2661,2672,2682,2693,2694,2698,2700,2714,2701,2689,2684,2664,2629,2610,2596,2594,2598,2585,2579,2573,2560,2542,2559,2548,2540,2533,2517,2513,2496,2518,2505,2504,2491,2462,2454,2435,2427,2434,2446,2431,2415,2408,2392,2371,2355,2349,2341,2329,2318,2316,2310,2304,2291,2283,2278,2252,2237,2230,2213,2204,2189,2183,2173,2163,2126,2098,2094,2083,2082,2056,2049,2030,2004,1987,1990,1990,1994,1995,1977,1973,1940,1901,1889,1873,1849,1835,1836,1827,1838,1824,1821,1813,1805,1794,1762,1744,1739,1726,1700,1689,1677,1653,1627,1612,1608,1612,1603,1584,1576,1581,1564,1552,1558,1557,1551,1535,1520,1520,1501,1471,1457,1455,1430,1415,1403,1397,1375,1367,1330,1335,1339,1334,1328,1339,1352,1352,1342,1327,1307,1300,1282,1262,1276,1298,1294,1299,1309,1309,1314,1308,1284,1273,1246,1247,1249,1238,1239,1270,1266,1255,1252,1237,1232,1236,1239,1236,1254,1245,1259,1281,1276,1262,1276,1284,1282,1296,1314,1337,1362,1368,1367,1376,1403,1408,1499,1499,1499,1499,1499,1499]}}],"ntuples":{},"info":{},"title":"referenceSpectrum"}

Output (8.2.5):
> {"spectra":[{"deltaX":null,"firstX":400,"lastX":2302,"xFactor":1,"yFactor":1,"isXYdata":true,"data":{"x":[400,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"y":[2861,2861,2861,2861,2861,2861,2861,3294,3623,3994,4536,4952,5364,5562,5842,5994,6263,6535,6993,7610,8368,9164,10006,10870,11849,12586,13494,14211,14937,15633,16255,16868,17694,18640,19698,20892,22154,23295,24076,24384,24252,23768,22870,21821,20601,19445,18354,17286,16364,15725,15222,14918,14837,14798,14936,15059,15005,14814,14630,14100,13389,12667,11835,10893,9832,8724,7714,6965,6224,5642,5596,5692,5705,5657,5660,5602,5506,5303,5074,4951,4780,4512,4155,3980,3770,3502,3340,3104,2904,2682,2473,2179,1956,1874,1733,1776,1692,1625,1570,1498,1367,1294,1324,1298,1319,1258,1279,1269,1326,1338,1344,1332,1313,1341,1340,1372,1475,1574,1673,1778,1866,2013,2085,2132,2258,2421,2487,2770,3035,3244,3374,3472,3480,3373,3064,2692,2482,2144,1911,1694,1611,1560,1569,1520,1491,1470,1377,1324,1204,1147,1144,1119,1080,1087,1061,1064,1095,1101,1132,1119,1102,1125,1120,1115,1111,1079,1106,1147,1112,1118,1143,1131,1147,1110,1078,1085,1157,1168,1173,1196,1244,1325,1361,1496,1688,1942,2271,2654,3194,3805,4559,5507,6566,7663,8953,10331,11904,13586,15497,17505,19544,21313,22820,23913,24742,25481,26192,27253,28206,29056,29601,29953,29871,29937,30316,31348,33361,35805,38517,41000,42967,44558,45874,47032,48579,50268,51758,52833,53173,52354,50350,47342,43500,39108,34337,29290,24457,19983,16171,13067,10914,9782,9422,9617,10084,10809,11550,12496,13447,14715,16358,18034,19818,21355,22473,23024,23132,22879,22574,22157,21664,21466,21332,21176,20818,20384,19736,18957,17987,17085,16237,15554,15046,14678,14565,14717,14916,15457,16078,16654,17011,17176,17173,16931,16341,15262,13988,12429,10677,8800,7248,5832,4690,3916,3135,2610,2204,1936,1753,1763,1816,1763,1612,1415,1241,1051,1014,1015,954,907,728,495,297,149,0,41,184,321,652,982,1498,2090,2726,3587,4721,6019,7410,8916,10341,11713,12818,13682,14479,15165,15764,16353,16974,17612,18309,19068,19870,20703,21621,22592,23354,23828,24044,23845,23509,22968,22348,21740,21427,21164,21013,20904,20894,20986,20925,20753,20478,20150,19672,19166,18718,18312,18087,17809,17521,17266,16969,16670,16405,16429,16582,16809,17184,17421,17440,17164,16605,15754,14861,13822,12405,10851,9024,7226,5505,3778,2556,1551,905,404,111,39,156,372,982,1673,2248,2574,2763,2569,2195,1525,914,497,166,16,39,316,644,1167,1801,2653,3735,4881,5961,6954,7842,8591,9293,9817,10142,10420,10394,10194,9785,9477,9077,8890,8709,8451,8162,7841,7471,6986,6622,6502,6619,6507,6759,6933,7085,7241,7422,7652,7933,8088,8003,8015,7844,7669,7407,7111,6617,6264,6065,5803,5719,5668,5696,5683,5686,6022,6433,6908,7330,7838,8372,8970,9734,10519,11327,11452,11346,10854,10134,9205,8608,8039,7810,7573,7397,7324,7206,7097,6799,6499,6361,6388,6295,6272,6461,6677,6871,6869,6945,6986,6907,6854,6775,6759,6847,6942,6866,6912,6859,6695,6537,6449,6661,7317,8367,9926,11933,14710,17855,21580,25578,29750,33822,37548,40851,43364,45309,46521,46660,45940,44554,42630,40365,37924,35269,32714,30200,27834,25423,22900,20123,17319,14550,11773,9208,7071,5540,4406,3533,2837,2396,2171,1857,1554,1335,1125,939,800,775,687,700,648,615,599,599,624,627,597,564,561,568,604,609,579,557,549,544,624,633,718,803,834,854,823,791,765,772,742,746,820,832,858,867,871,861,856,901,948,974,1000,1000,1044,1088,1106,1133,1161,1161,1170,1171,1146,1172,1214,1251,1259,1309,1340,1368,1381,1407,1403,1430,1439,1439,1472,1487,1501,1525,1570,1591,1625,1690,1726,1738,1780,1832,1836,1860,1837,1823,1833,1792,1768,1830,1883,1911,1916,1923,1930,1921,1915,1931,1943,1981,2000,2012,2020,2061,2081,2089,2086,2072,2101,2114,2122,2137,2174,2182,2174,2187,2201,2222,2237,2253,2244,2240,2234,2255,2279,2300,2290,2285,2284,2282,2303,2333,2374,2410,2418,2435,2435,2447,2452,2455,2480,2490,2478,2472,2481,2492,2524,2556,2566,2579,2563,2569,2583,2592,2605,2629,2641,2638,2633,2619,2630,2646,2676,2695,2725,2726,2726,2716,2701,2693,2686,2703,2706,2704,2703,2696,2696,2683,2685,2705,2732,2728,2732,2736,2719,2739,2729,2746,2760,2761,2725,2721,2655,2703,2771,2808,2820,2818,2814,2793,2760,2704,2728,2718,2698,2665,2655,2648,2661,2672,2682,2693,2694,2698,2700,2714,2701,2689,2684,2664,2629,2610,2596,2594,2598,2585,2579,2573,2560,2542,2559,2548,2540,2533,2517,2513,2496,2518,2505,2504,2491,2462,2454,2435,2427,2434,2446,2431,2415,2408,2392,2371,2355,2349,2341,2329,2318,2316,2310,2304,2291,2283,2278,2252,2237,2230,2213,2204,2189,2183,2173,2163,2126,2098,2094,2083,2082,2056,2049,2030,2004,1987,1990,1990,1994,1995,1977,1973,1940,1901,1889,1873,1849,1835,1836,1827,1838,1824,1821,1813,1805,1794,1762,1744,1739,1726,1700,1689,1677,1653,1627,1612,1608,1612,1603,1584,1576,1581,1564,1552,1558,1557,1551,1535,1520,1520,1501,1471,1457,1455,1430,1415,1403,1397,1375,1367,1330,1335,1339,1334,1328,1339,1352,1352,1342,1327,1307,1300,1282,1262,1276,1298,1294,1299,1309,1309,1314,1308,1284,1273,1246,1247,1249,1238,1239,1270,1266,1255,1252,1237,1232,1236,1239,1236,1254,1245,1259,1281,1276,1262,1276,1284,1282,1296,1314,1337,1362,1368,1367,1376,1403,1408,1499,1499,1499,1499,1499,1499]}}],"ntuples":{},"info":{},"meta":{},"title":"referenceSpectrum"}
