### ISSUE TITLE
Parsing 2D FID

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/jcampconverter#70]
We can copy the 2D FID from this example: https://github.com/cheminfo/nmrium/blob/e7fa46bc01cd93f80d0d5104a42d3e83edebfd92/public/data/cytisine/2d/COSY_Cytisin.dx#L7-L8

We should only keep the block related to the 2D fid.

We need to find a way to deal correctly with those data and return something that can be further processed by nmr-load-save.

Using those 2 options:

- keepSpectra: true
- noContour: true

You should get all the original spectra that should be converted to a rr, ii matrices by `nmr-load-save`

 * @property {boolean} [options.keepSpectra=false] - Force to keep the spectra in case of 2D.
 * @property {boolean} [options.noContour=false] - Don't calculate countour in case of 2D.

**Comment by lpatiny** [comment]
Seems to me this is working correctly now. @jobo322 can we close this issue ?

**Comment by jobo322** [comment]
yes, there is a PR in nmr-load-save package that ensure keep spectra and no generation of contours.

- https://github.com/cheminfo/nmr-load-save/pull/127
